#!/bin/bash
# This script adds the file's creation time as timestamp to the given filename
# Copyright 2017 by Reiner Rottmann. Released under the BSD License.
if [ -z "$1" ]; then
    echo "Usage: $0 <file>"
    exit 1
fi
which stat > /dev/null
if ! [ "$?" -eq 0 ]; then
    echo "Not running on a POSIX system."
    exit 1
fi
dn=`dirname "$1"`
fn=`basename "$1"`
echo "$fn" | grep -Eq "^[0-9]{6}-"
if [ "$?" -eq 0 ]; then
    echo "Timestamp already present."
    exit 0
fi
uname -s | grep -q Darwin
if [ "$?" -eq 0 ]; then
    # running on Darwin
    ts=`stat -x -t"%y%m%d" "$1" | grep ^Change: | cut -d ':' -f2- | tr -d ' '`
    echo "$1" "$dn/$ts-$fn" >> ~/foo.txt
    mv "$1" "$dn/$ts-$fn"
else
    # not running on Darwin"
    ts=`stat -c"%y%m%d" "$1" | grep ^Change: | cut -d ':' -f2- | tr -d ' '`
    ts=`date -d "$ts" "+%y%m%d"`
    mv "$1" "$dn/$ts-$fn"
fi
exit 0
