#!/bin/sh
# This script will remove lvm2 clones of the os volumes.
# Copyright 2013 by Reiner Rottmann (reiner@rottmann.it). Released under the BSD License.
rootvol=`df -hP / |grep ^/ |cut -d ' ' -f1`
rootvg=`basename $rootvol |cut -d '-' -f1`
clonepostfix=_clone  # postfix for the clone name

# preflight checks
if ! uname -r |grep -q el6; then
   echo "ERROR: This script needs to be run on RHEL 6."
   exit 1
fi
if [ -z "$rootvol" ]; then
   echo "ERROR: Could not determine the root volume."
   exit 1
fi
if [ -z "$rootvg" ]; then
   echo "ERROR: Could not determine the lvm2 volume group of the root volume."
   exit 1
fi
# remove the clone of each lv on the vg with the root volume
lvs $rootvg --noheadings | grep "$clonepostfix" | while read clone foo
do
   cmd="lvremove --force $rootvg/$clone"
   echo "# $cmd"
   $cmd
done
